baseURL = "https://coopcycle.org/"
theme = "coopcycle"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[blackfriday]
extensions = ["hardLineBreak"]

[Taxonomies]

[Languages]

### English

[Languages.en]
title = "CoopCycle"
description = "CoopCycle is the European network of bike delivery coops."

### French

[Languages.fr]
title = "CoopCycle"
description = "CoopCycle est la fédération européenne des coopératives de livraison à vélo."

### Spanish

[Languages.es]
title = "CoopCycle"
description = "CoopCycle es un software para administrar una plataforma logística."

[[Languages.fr.menu.main]]
name = "Blog"
weight = 4
identifier = "blog"
url = "https://blogs.mediapart.fr/coopcycle"

