name: Build
on:
  push:
    branches:
      - master
jobs:
  JSON_LINT:
    name: JSON Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install jsonlint
        run: npm install -g jsonlint
      - name: Lint JSON file
        run: jsonlint data/coops.json
