name: Build

on: [push]

jobs:
  JSON_LINT:
    name: JSON Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install jsonlint
        run: npm install -g jsonlint
      - name: Lint JSON file
        run: jsonlint data/coops.json
  HUGO_BUILD:
    name: Build website with Hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.52'
      - name: Install jsonschema
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Install JS dependencies
        working-directory: ./themes/coopcycle
        run: |
          npm ci
          npm run build
          npm prune
      - name: Build
        run: hugo
      - name: Validate JSON schema
        run: jsonschema --instance public/coopcycle.json coopcycle.schema
